### PR TITLE
Prebuild for arm64 for Linux and Windows

### LINKED ISSUE #225: prebuild: doesn't have arm-64
* Why doesn't the prebuild have arm64? I'm using this dependency in a VSCode extension and because of this I get error 

`failed: No native build was found for platform=linux arch=arm64 runtime=electron abi=108 uv=1 armv=8 libc=glibc node=18.18.2`

* Upon a look on node modules I saw this.
image

### PR DESCRIPTION
**Pull request by verhovsky**
Closes #225

### CODE REVIEW

**Comment by shivamsouravjha** [comment]
@ObserverOfTime please review this as

**Comment by ObserverOfTime** [comment]
Bumping `node-gyp-build` to v4.8.2 may or may not fix this.
Might as well bump all the deps while you're at it and/or set up dependabot.

**Comment by ObserverOfTime** [comment]
Try lowering the Python version to 3.11 with `actions/setup-python`.

If that doesn't work, disable Node 22 on Windows. ¯\\\_(ツ)\_/¯

**Comment by shivamsouravjha** [comment]
Any idea when we can see this in release? Very much keen in seeing this released

**Pull request merged**
