### PR TITLE
Update tree-sitter to 0.15.1

### PR DESCRIPTION
**Pull request by Razzeee**
So I think this might be what's needed? Not sure if there is something else that needs to be done.

Closes https://github.com/tree-sitter/node-tree-sitter/issues/40

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
PR #39 actually already updates to Tree-sitter 0.15. It's working, but I'm holding off for a little bit because I want to wait until I get Tree-sitter updated in Atom.

**Comment by maxbrunsfeld** [comment]
@Razzeee in the meantime, I might suggest using version 0.14.x of Tree-sitter CLI to generate your parser.

**Comment by Razzeee** [comment]
Yeah, I figured that downgrading would be an option, but hoped I would be able to role forward and don't have to push new releases to npm and github. Hoped it was just an oversight. But might as well do role back, if the timeline is unclear.

Thx, for letting me know. Should I close this PR?

**Comment by maxbrunsfeld** [comment]
I think this is taken care of via https://github.com/tree-sitter/node-tree-sitter/pull/39.

**Pull request closed without merging**
