### PR TITLE
Attempt to update query handling based on 'web-tree-sitter/binding.js'

### PR DESCRIPTION
**Pull request by restlessronin**
I took a crack at fixing Issue #179. I basically borrowed the equivalent code from the "official" tree-sitter 'binding.js', modifying it a little bit. I believe it is mostly corrrect, but I have been unable to test it, since I cannot get this repo to build correctly. Node is not my primary environment and I do not currently have the time to debug the build process / dependencies, etc.

I'm hoping that someone who has the repo building correctly has the time to take my changes and do the final refinements to get this working and test it.

I'm working on downstream code that would benefit.

### CODE REVIEW

**Comment by restlessronin** [comment]
Any chance of enabling the running of the test workflow? If it succeeds the changes have not broken anything. If it fails, hopefully the error messages provide enough information to complete the PR.

**Comment by restlessronin** [comment]
The CI action is failing on *all* the macos tests. The failure is occurring at the 'npm install' stage (which is the same problem I had on my dev machine - a mac M1). I notice that the last couple of open PR's seem to have the same failure.

The good news is that it's passing on linux and windows. SInce all my changes are to the "index.js" file, this means that my PR hasn't broken anything that's being tested.

Perhaps someone on Windows and Linux could test that the PR works as it's supposed to on some of the newer predicates? 

Or if someone can fix the broken macos install (I don't know enough about node to be able to do it in a reasonable amount of time), I would be happy to fully test the functionality on my mac.

**Comment by verhovsky** [comment]
The CI is fixed, if you want to rebase onto master.

**Comment by restlessronin** [comment]
@verhovsky I have added tests for the new predicates. In order to get them to pass, I had to fix some "bugs". If my understanding of the semantics is correct, these bugs are also present in the original repo. I have submitted a PR for that as well. It would be best for that PR to be accepted before proceeding with this, because it will confirm that the tests reflect an accurate understanding of the predicate semantics.

I also need to test the default switch branch, which seems to be for custom predicates defined in the grammar. I will attempt to do so and complete this PR in the next day or so.

**Comment by restlessronin** [comment]
It appears that changing the default branch of the operator switch expression requires more work than I have the time for. As such, I've reverted it back to throwing an error.

@verhovsky this PR should now be good to go, once the PR fix for the original repo has been validated.

**Comment by verhovsky** [comment]
That's just a random person

**Comment by restlessronin** [comment]
Ah. Since I can't approve a PR in that repo (only the "comment" button is enabled), I assumed only someone with write or higher access could review it. My bad.

**Comment by restlessronin** [comment]
@verhovsky the original repo has now updated the code (they used an earlier PR that fixed the bug, and not mine). I therefore replicated the new code for quantifiers, as well as the new test. One of the other tests seems to have broken in the meantime, which seems like it may be caused by a new javascript grammar (the dependency in package.json is to "tree-sitter-javascript": "https://github.com/tree-sitter/tree-sitter-javascript.git#master" which seems non-deterministic)

In any case, I believe the predicate code is now working the same as in the main repo (same code and tests are passing).

**Comment by restlessronin** [comment]
@verhovsky does anything else need to be done to merge this feature enhancement.

**Comment by amaanq** [comment]
@restlessronin does this have the same tests as upstream's bindings? I think it does but I'd like to double check - I can merge then if so

**Comment by amaanq** [comment]
thanks!

**Comment by restlessronin** [comment]
> @restlessronin does this have the same tests as upstream's bindings? I think it does but I'd like to double check with you - I can merge then if so

As you probably figured out already, it's basically a direct copy (with two small changes to accommodate different syntaxes).

**Pull request merged**
